name: Build and Publish

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner for Visual Studio 2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSVC tools
        uses: ilammy/msvc-dev-cmd@v1  # Import MSVC++ tools for Visual Studio 2019

      - name: Compile project
        run: |
          cd unicorn_pe  # Navigate to the project directory
          "C:\Program Files\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe" /p:Configuration=Release /p:Platform=x64  # Compile the project

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled-builds
          path: unicorn_pe/bin/x64/Release  # Adjust the path to your compiled binaries
